INSERT INTO yacht_models (make, model, year, length_overall, beam_width, draft_depth, keel_type_id, fuel_type_id, created_at) VALUES
                                                                                                                      ('Beneteau', 'Oceanis 46.1', 2020, 14.60, 4.50, 2.05, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'First 53', 2020, 17.16, 4.99, 2.40, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Oceanis 51.1', 2019, 15.94, 4.80, 2.36, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Oceanis 38.1', 2018, 11.50, 3.99, 2.08, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Oceanis Yacht 62', 2021, 19.16, 5.33, 2.98, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'First 27', 2019, 7.99, 2.54, 1.80, 5, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'First 24', 2018, 7.29, 2.50, 1.80, 5, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Oceanis 35.1', 2017, 10.45, 3.72, 1.85, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Gran Turismo 40', 2018, 12.67, 3.85, 1.15, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Gran Turismo 50', 2019, 15.78, 4.38, 1.30, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Swift Trawler 41', 2020, 13.43, 4.20, 1.15, 7, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Swift Trawler 35', 2018, 11.29, 4.03, 1.17, 7, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Antares 8', 2021, 8.23, 2.76, 0.60, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Antares 11', 2020, 11.16, 3.40, 0.70, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Barracuda 9', 2019, 9.00, 2.95, 0.50, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Figaro Beneteau 3', 2018, 10.30, 3.40, 2.50, 6, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Oceanis 30.1', 2019, 9.53, 2.99, 1.88, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'Oceanis 40.1', 2021, 12.87, 4.18, 1.94, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'First 14', 2018, 4.30, 1.70, 0.30, 5, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Beneteau', 'First 18', 2019, 5.55, 2.38, 0.30, 5, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Odyssey 410', 2020, 12.35, 3.99, 2.14, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Odyssey 490', 2021, 14.42, 4.49, 2.24, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Odyssey 440', 2022, 13.39, 4.29, 2.20, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Fast 3600', 2018, 11.25, 3.55, 2.13, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Jeanneau 64', 2019, 20.10, 5.40, 2.95, 7, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Odyssey 349', 2021, 10.34, 3.44, 1.98, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'NC 37', 2020, 11.47, 3.59, 0.96, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Leader 40', 2019, 12.33, 3.80, 1.10, 8, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Merry Fisher 895', 2022, 8.90, 2.99, 0.63, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Cap Camarat 7.5 WA', 2021, 7.74, 2.52, 0.55, 10, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Odyssey 519', 2018, 15.75, 4.69, 2.28, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Sun Fast 3300', 2020, 10.11, 3.40, 2.00, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Merry Fisher 1095', 2019, 10.50, 3.35, 0.69, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Leader 46', 2020, 14.30, 4.10, 1.25, 8, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'NC 795', 2021, 7.90, 2.81, 0.50, 10, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Cap Camarat 9.0 CC', 2022, 9.12, 2.98, 0.65, 10, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Yacht 54', 2021, 16.16, 4.92, 2.50, 6, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Merry Fisher 695 Serie2', 2022, 6.55, 2.54, 0.46, 10, 5, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'Leader 36', 2020, 11.47, 3.62, 1.30, 8, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Jeanneau', 'NC 33', 2019, 10.50, 3.32, 0.96, 10, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Amel', 'Super Maramu', 2000, 16.00, 4.60, 2.05, 7, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Amel', '50', 2020, 15.51, 4.79, 2.15, 7, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Amel', '55', 2015, 17.30, 4.99, 2.20, 7, 2, CURRENT_TIMESTAMP),
                                                                                                                      ('Amel', '64', 2010, 19.60, 5.60, 2.50, 7, 2, CURRENT_TIMESTAMP);
