ALTER TABLE `vessels`
ADD COLUMN `created_by` VARCHAR(20) NOT NULL,
ADD COLUMN `updated_at` DATE DEFAULT NULL,
ADD COLUMN `updated_by` VARCHAR(20) DEFAULT NULL;

ALTER TABLE `keel_types`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `fuel_types`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `yacht_models`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `countries`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `towns`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `locations`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `yacht_images`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `owner_infos`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `yacht_details`
ADD COLUMN `created_at` DATETIME NOT NULL,
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

ALTER TABLE `yachts`
ADD COLUMN `updated_at` DATETIME DEFAULT NULL;

GO